api-version: 1.17
main: com.kicasmads.cs.ChestShops
name: ChestShops
description: A simple plugin for chest shops
authors: [Kishiko73, maddymakesgames, xCassyx, funnyboy_roks, Majekdor]
version: 1.0
commands:
  shops:
    description: View a player's shops
    usage: /shops [me|playername]
  searchshops:
    description: Search for a specific item being sold or bought
    usage: /searchshops <item> [sell|buy]
permissions:
  cs.shops.destroy-unowned:
    description: Allows a player to destroy a shop they don't own
    default: op